replace command line argument parsing of history command with cli parser

diff --git a/share/arsh/modules/repl_impl/history b/share/arsh/modules/repl_impl/history
--- a/share/arsh/modules/repl_impl/history
+++ b/share/arsh/modules/repl_impl/history
@@ -40,6 +40,29 @@ function _usage(fd : UnixFD, short : Boolean) : Int {
     return 2
 }
 
+[<CLI(desc: "Display or manipulate history list.")>]
+typedef _HistParam() {
+    [<Flag(short: "c", help: "clear the history list", stop: $true)>]
+    var clear = $false
+
+    [<Option(short: 'd', placeholder: 'offset', help: "delete the history entry at OFFSET")>]
+    var del : Int?
+
+    [<Flag(short: 's', stop: $true, help: "append the remain ARGs to history as single entry")>]
+    var append = $false
+
+    [<Option(short: 'r', long: "read", opt: $true, default: "", placeholder: "file", 
+            help: "read the history list from FILE")>]
+    var load : String?
+
+    [<Option(short: "w", long: "write", opt: $true, default: "", placeholder: "file", 
+            help: "write the history list to FILE")>]
+    var save: String?
+
+    [<Arg>]
+    var args: [String]
+}
+
 function _show(argv : [String]) : Int {
     let histSize = $HISTORY.size()
     let size = $argv.size()
@@ -121,17 +144,17 @@ function _add_and_save(s : String) {
     }
 }
 
-function _load(p : String?) {
+function _load(path : String) {
     $HISTSIZE == 0 && return;
-    if !$p || $p!.empty() { $p = $HISTFILE; }
-    let path = try { $p!.realpath() } catch e { return; }
+    if $path.empty() { $path = $HISTFILE; }
+    $path = try { $path.realpath() } catch e { return; }
     for $line in $STDIN {
         $_add($line)
     } with < $path
     $PIPESTATUS.clear()
 }
 
-function _save(p : String?) {
+function _save(path : String) {
     if $HISTFILESIZE > $_HISTLIMIT {
         $HISTFILESIZE = $_HISTLIMIT
     }
@@ -140,8 +163,7 @@ function _save(p : String?) {
         return;
     }
 
-    if !$p || $p!.empty() { $p = $HISTFILE; }
-    let path = $p!
+    if $path.empty() { $path = $HISTFILE; }
     let size = $HISTORY.size()
     var offset = $size < $HISTFILESIZE ? 0 : $size - $HISTFILESIZE
     $offset < $size || return
@@ -155,69 +177,40 @@ function _save(p : String?) {
     chmod g-rw,o-rw $path
 }
 
-history() {
+history(param : _HistParam) {
     $_sync()
 
     if($# == 0 || $@[0][0] != '-') {
         return $_show($@)
     }
 
-    var op = ""
-    var fileName : String?
-    var deleteTarget = ""
-
-    for(var i = 0; $i < $#; $i++) {
-        let arg = $@[$i]
-        case $arg {
-        '-c' => { $HISTORY.clear(); return 0; }
-        '-d' => {
-            if $i + 1 < $# {
-                $i++
-                $deleteTarget = $@[$i]
-                continue
-            }
-            $_error("$arg: option requires argument")
-            return 2
-        }
-        '-h' => { $_usage($STDOUT, $false); return 0; }
-        '-s' => {
-            var line = ""
-            for($i++; $i < $#; $i++) {
-                if !$line.empty() { $line += " "; }
-                $line += $@[$i]
-            }
-            $_add($line)
-            return 0;
-        }
-        '-r' | '-w' => {
-            if !$op.empty() {
-                $_error("cannot use more than one of -rw")
-                return 1
-            }
-            $op = $arg
-            if $i + 1 < $# && $@[$i + 1][0] != "-" {
-                $i++;
-                $fileName = $@[$i]
-            }
-            continue
-        }
-        else => { $_error("$arg: invalid option"); return $_usage($STDERR, $true); }
-        }
-    }
-
-    if !$deleteTarget.empty() {
-        var offset = $deleteTarget.toInt()
-        if !$offset || $offset! < 1 || $offset! > $HISTORY.size() {
-            $_error("$deleteTarget: history offset out of range")
-            return 1
-        }
-        $HISTORY.remove($offset! - 1)
+    if $param.clear {
+        $HISTORY.clear()
         return 0
     }
-
-    case $op {
-    '-r' => $_load($fileName)
-    '-w' => $_save($fileName)
+    if $param.append {
+        var line = $param.args.join(" ")
+        $_add($line)
+        return 0
+    }
+    if let offset = $param.del {
+        if $offset < 1 || $offset > $HISTORY.size() {
+            echo 1>&2 ${$param.usage("$offset: history offset out of range", $false)}
+            return 1
+        }
+        $HISTORY.remove($offset - 1)
+        return 0
+    }
+    if $param.load || $param.save {
+        if($param.load && $param.save) {
+            echo 1>&2 ${$param.usage("cannot use more than one of -rw", $false)}
+            return 1
+        }
+        if let target = $param.load {
+            $_load($target)
+        } elif let target = $param.save {
+            $_save($target)
+        }
     }
     return 0
 }
