check llvm-cov in clang-gcov

diff --git a/clang-gcov b/clang-gcov
--- a/clang-gcov
+++ b/clang-gcov
@@ -1,3 +1,9 @@
 #!/bin/sh
 
+which llvm-cov > /dev/null
+if [ $? != 0 ]; then
+    echo '-- llvm-cov is not found ---' 1>&2
+    exit 1
+fi
+
 exec llvm-cov gcov $@
